### ISSUE TITLE
REPORTE DE PRÁCTICA DE HILOS.

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/practica-de-hilos-Rigoberto2001#2]
[REPORTEPRÁCTICA_HILOS_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Rigoberto2001/files/6497567/REPORTEPRACTICA_HILOS_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 19.4

Calificó: Imanol García, Israel Nicolás y Uzias López

**Comment by josealfredo79** [comment]
bien hecho y revisado
